export const C = {
  bg: "#0d0a0a",
  surfaceContainer: "#1e1918",
  surfaceContainerHigh: "#2d2423",
  onSurface: "#ffffff",
  onSurfaceVariant: "#e2d2d0",
  primary: "#ff3b30",
  onPrimary: "#ffffff",
  primaryContainer: "#aa000f",
  onPrimaryContainer: "#ffffff",
  error: "#ff3b30",
  blueContainer: "#005ea2",
  onBlueContainer: "#ffffff",
  greenContainer: "#198754",
  onGreenContainer: "#ffffff",
  yellowContainer: "#ffd60a",
  onYellowContainer: "#000000",
  sosRed: "#ff3b30",
};
