import { precacheAndRoute } from 'workbox-precaching';

// Automatically precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Keep our custom background timer logic intact below

// Background Safety Check Timer
let safetyTimer = null;

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "START_SAFETY_TIMER") {
    const { intervalMs } = event.data;
    console.log(`[Service Worker] Starting background safety check timer for ${intervalMs}ms`);
    
    if (safetyTimer) {
      clearInterval(safetyTimer);
    }
    
    safetyTimer = setInterval(() => {
      self.registration.showNotification("RoadSOS Safety Check", {
        body: "Are you safe? Tap to open the app and confirm.",
        icon: "/favicon.svg",
        vibrate: [300, 100, 300],
        tag: "roadsos-safety-check",
        requireInteraction: true,
        data: { url: "/" }
      });
    }, intervalMs);
  } else if (event.data && event.data.type === "CANCEL_SAFETY_TIMER") {
    console.log("[Service Worker] Safety check timer cancelled.");
    if (safetyTimer) {
      clearInterval(safetyTimer);
      safetyTimer = null;
    }
  }
});

// Handle notification click to open the PWA
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((clientList) => {
      // Focus existing window
      for (const client of clientList) {
        if ("focus" in client) {
          return client.focus();
        }
      }
      // Or open a new window
      if (clients.openWindow) {
        return clients.openWindow("/");
      }
    })
  );
});
